import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: "#F1F2F6",
    },
    container: {
        flex: 1,
        backgroundColor: "#F1F2F6",
    },
    header: {
        backgroundColor: "#1B1B1B",
        paddingBottom: 25,
        paddingTop: 20,
    },
    headerContent: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: 25,
        paddingTop: 15,
        position: "relative",
    },

    homeButton: {
        backgroundColor: "#FFFFFF",
        borderRadius: 25,
        padding: 8,
        position: "absolute",
        left: 25,
        top: 15,
        zIndex: 1,
        alignItems: "center",
        justifyContent: "center",
        width: 45,
        height: 45,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    logoContainer: {
        alignItems: "center",
        marginBottom: 25,
    },
    logoText: {
        fontSize: 28,
        fontWeight: "bold",
        color: "#ffffFF",
        letterSpacing: 2,
    },
    welcomeSection: {
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 10,
    },
    sectionTitle: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#1A202C",
        marginBottom: 4,
    },
    sectionSubtitle: {
        fontSize: 14,
        color: "#4A5568",
        marginBottom: 16,
    },
    mainContent: {
        flex: 1,
        padding: 25,
        backgroundColor: "#F1F2F6",
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
        marginTop: -15,
    },
    listContent: {
        paddingHorizontal: 20,
        paddingBottom: 20,
        flexGrow: 1,
    },
    viagemCard: {
        borderRadius: 12,
        marginBottom: 16,
        elevation: 5,
        overflow: "hidden",
        borderColor: "#E2E8F0",
        borderWidth: 1,
    },
    cardGradient: {
        borderRadius: 12,
        overflow: "hidden",
        backgroundColor: "#FFFFFF",
        borderColor: "black",
    },
    viagemHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#E3F2FD",
        backgroundColor: "#1A365D",
    },
    routeContainer: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
    },
    routeText: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#E3F2FD",
        marginLeft: 8,
        flex: 1,
    },
    statusBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 20,
        backgroundColor: "#FFDDAA",
    },
    statusText: {
        fontSize: 12,
        fontWeight: "bold",
        color: "#FF8C00",
    },
    detailsContainer: {
        padding: 16,
        backgroundColor: "#FFFFFF",
        borderBottomWidth: 1,
        borderBottomColor: "#E2E8F0",
    },
    detailRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 8,
    },
    icon: {
        marginRight: 8,
        width: 16,
        color: "#FFFFFF",
    },
    detailLabel: {
        fontSize: 14,
        color: "#4A5568",
        width: 90,
    },
    logoImageContainer: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: "#FFFFFF",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 10,
        borderWidth: 2,
        borderColor: "#FF8C00",
    },
    logoSubtext: {
        fontSize: 11,
        color: "#E2E8F0",
        marginBottom: 8,
        fontWeight: "500",
    },
    logoUnderline: {
        width: 50,
        height: 3,
        backgroundColor: "#FF8C00",
        borderRadius: 2,
    },
     logoImage: {
        width: 35,
        height: 35,
    },
    detailValue: {
        fontSize: 14,
        color: "#FF8C00",
        fontWeight: "500",
        flex: 1,
    },
    cardFooter: {
        flexDirection: "row",
        borderTopWidth: 1,
        borderTopColor: "#E2E8F0",
        padding: 12,
        justifyContent: "center",
        backgroundColor: "#F8F9FA",
    },
    cardAction: {
        flexDirection: "row",
        alignItems: "center",
        marginHorizontal: 15,
    },
    cardActionText: {
        marginLeft: 6,
        fontSize: 13,
        fontWeight: "bold",
    },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingVertical: 60,
    },
    loadingText: {
        color: "#A0AEC0",
        marginTop: 10,
        fontSize: 16,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingVertical: 60,
    },
    emptyText: {
        color: "#A0AEC0",
        fontSize: 18,
        fontWeight: "bold",
        marginTop: 16,
    },
    emptySubText: {
        color: "#A0AEC0",
        fontSize: 14,
        marginTop: 8,
        textAlign: "center",
    },
});
