import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#F1F2F6",
    },
    header: {
        backgroundColor: "#1B1B1B",
        paddingBottom: 25,
        paddingTop: 20,
    },
    headerContent: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: 25,
        paddingTop: 15,
        position: "relative",
    },
    homeButton: {
        backgroundColor: "#FFFFFF",
        borderRadius: 25,
        padding: 8,
        position: "absolute",
        left: 25,
        top: 15,
        zIndex: 1,
        alignItems: "center",
        justifyContent: "center",
        width: 45,
        height: 45,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    logoContainer: {
        alignItems: "center",
        marginBottom: 25,
    },
    logoImageContainer: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: "#FFFFFF",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 10,
        borderWidth: 2,
        borderColor: "#FF8C00",
    },
    logoImage: {
        width: 35,
        height: 35,
    },
    buttonText: {
        fontSize: 16,
        fontWeight: "600",
        color: "white",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    logoText: {
        fontSize: 28,
        fontWeight: "bold",
        color: "#FFFFFF",
        letterSpacing: 2,
    },
    logoSubtext: {
        fontSize: 11,
        color: "#E2E8F0",
        marginBottom: 8,
        fontWeight: "500",
    },
    imagePreview: {
        width: "100%",
        height: 200,
        borderRadius: 8,
        marginTop: 10,
        resizeMode: "cover",
        borderWidth: 2,
        borderColor: "#3A3F5A",
    },
    textArea: {
        height: 80,
        textAlignVertical: "top",
        paddingTop: 12,
    },
    buttonDisabled: {
        opacity: 0.6,
    },
    flatListContent: {
        paddingBottom: 40,
        flexGrow: 1,
    },
    qrCodeScannerContainer: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "black",
        justifyContent: "center",
        alignItems: "center",
        zIndex: 1000,
    },
    logoUnderline: {
        width: 50,
        height: 3,
        backgroundColor: "#FF8C00",
        borderRadius: 2,
    },
    mainContent: {
        flex: 1,
        padding: 25,
        backgroundColor: "#F1F2F6",
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
        marginTop: -15,
    },
    formTitle: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#1A202C",
        marginBottom: 20,
        textAlign: "center",
    },
    fieldContainer: {
        marginBottom: 20,
    },
    label: {
        fontSize: 14,
        fontWeight: "500",
        color: "#4A5568",
        marginBottom: 8,
    },
    input: {
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: "#E2E8F0",
        fontSize: 16,
        color: "#1A202C",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    submitButton: {
        backgroundColor: "#FF8C00",
        marginTop: 20,
    },
    button: {
        backgroundColor: "#FF8C00",
        padding: 15,
        borderRadius: 12,
        alignItems: "center",
        marginBottom: 20,
        height: 50,
        justifyContent: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    pickerInput: {
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: "#E2E8F0",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    pickerText: {
        fontSize: 16,
        color: "#1A202C",
    },
    pickerPlaceholderText: {
        fontSize: 16,
        color: "#A0AEC0",
    },
    infoContainer: {
        backgroundColor: "#FFF5E6",
        padding: 15,
        borderRadius: 12,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: "#FF8C00",
    },
    infoText: {
        fontSize: 14,
        color: "#1A202C",
    },
    infoLabel: {
        fontWeight: "bold",
        color: "#FF8C00",
    },
    flatListContainer: {
        flex: 1,
        marginTop: 10,
        paddingBottom: 10,
    },
    noDataText: {
        textAlign: "center",
        marginTop: 20,
        color: "#888",
        paddingVertical: 20,
    },
    viagemCard: {
        borderRadius: 12,
        marginBottom: 16,
        elevation: 5,
        overflow: "hidden",
        borderColor: "#E2E8F0",
        borderWidth: 1,
    },
    cardGradient: {
        borderRadius: 12,
        overflow: "hidden",
        backgroundColor: "#FFFFFF",
    },
    detailsContainer: {
        padding: 16,
        backgroundColor: "#FFFFFF",
    },
    detailRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 8,
    },
    detailLabel: {
        fontSize: 14,
        color: "#4A5568",
        width: 90,
    },
    detailValue: {
        fontSize: 14,
        color: "#1A365D",
        fontWeight: "500",
        flex: 1,
    },
    icon: {
        marginRight: 8,
        width: 16,
        color: "#FF8C00",
    },
});
