import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    rowContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 0,
    },
    halfWidth: {
        width: "48%",
    },
    fieldContainer: {
        width: "100%",
        marginBottom: 20,
    },
    infoContainer: {
        backgroundColor: "#FFF5E6",
        padding: 15,
        borderRadius: 12,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: "#FF8C00",
    },
    label: {
        fontSize: 14,
        fontWeight: "500",
        color: "#1A202C",
        marginBottom: 8,
    },
    pickerInput: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        width: "100%",
        height: 50,
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: "#E2E8F0",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    input: {
        width: "100%",
        height: 50,
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        paddingHorizontal: 16,
        color: "#1A202C",
        fontSize: 16,
        borderWidth: 1,
        borderColor: "#E2E8F0",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    button: {
        width: "100%",
        height: 50,
        backgroundColor: "#1A365D",
        borderRadius: 12,
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
        marginBottom: 20,
    },
    submitButton: {
        backgroundColor: "#FF8C00",
        marginTop: 10,
    },
    backButton: {
        backgroundColor: "#1A365D",
    },
    infoText: {
        fontSize: 14,
        color: "#1A202C",
        marginBottom: 5,
    },
    infoLabel: {
        fontWeight: "bold",
        color: "#FF8C00",
    },
    checkbox: {
        flexDirection: "row",
        alignItems: "center",
        height: 50,
        paddingHorizontal: 10,
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#E2E8F0",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        width: "100%",
    },
    checkboxLabel: {
        marginLeft: 8,
        fontSize: 16,
        color: "#1A202C",
    },
    pickerText: {
        fontSize: 16,
        color: "#1A202C",
    },
    pickerPlaceholderText: {
        fontSize: 16,
        color: "#A0AEC0",
    },
    textArea: {
        height: 120,
        textAlignVertical: "top",
        paddingTop: 12,
    },
    buttonText: {
        fontSize: 16,
        fontWeight: "600",
        color: "#FFFFFF",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
   
    inputText: {
        color: "#000",
        fontSize: 16,
    },
   
    pickerContainer: {
        borderWidth: 2,
        borderColor: "#3A3F5A",
        borderRadius: 8,
        backgroundColor: "white",
        overflow: "hidden",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
    },
    picker: {
        width: "100%",
        height: 50,
        color: "#000",
    },
    pickerItem: {
        fontSize: 16,
    },
    checkboxContainer: {
        flexDirection: "column",
        alignItems: "flex-start",
        width: "48%",
    },
     buttonDisabled: {
        opacity: 0.6,
    },
});